version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: fe_runner
      args:
        FE_DIR: ${FE_DIR:-frontend}
        NODE_IMAGE: ${NODE_IMAGE:-node:lts-alpine}
    env_file: .env
    environment:
      NUXT_PORT: ${NUXT_PORT:-3000}
      NITRO_PORT: ${NUXT_PORT:-3000}
    ports:
      - "${NUXT_PORT:-3000}:3000"
    depends_on: [backend]
    networks: [appnet]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: be_runner
      args:
        BE_DIR: ${BE_DIR:-backend}
        NODE_IMAGE: ${NODE_IMAGE:-node:lts-alpine}
    env_file: .env
    environment:
      NODE_ENV: production
      # --- SQLite config ---
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /opt/app/.tmp/data.db
      # Strapi secrets (set your own real values)
      APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${STRAPI_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${STRAPI_ADMIN_JWT_SECRET}
      JWT_SECRET: ${STRAPI_JWT_SECRET}
      URL: ${STRAPI_URL:-http://localhost:1337}
    ports:
      - "${STRAPI_PORT:-1337}:1337"
    volumes:
      - strapi_uploads:/opt/app/public/uploads
      - strapi_data:/opt/app/.tmp        # persists SQLite file
    networks: [appnet]

networks:
  appnet: {}      # empty is fine (named network with defaults)

volumes:
  strapi_uploads: {}
  strapi_data: {} # named volume for SQLite database
